(require :desktop-entry)
(in-package #:desktop-entry)
(format t "====================~%")
(add-to-entry-list (get-entry-from-desktop-file #P"/usr/share/applications/google-chrome.desktop"))
(add-to-entry-list #P"/usr/share/applications/google-chrome.desktop")
(format t "first entry: ~S~%" (categories (first *entry-list*)))
(format t "second entry: ~S~%" (categories (second *entry-list*)))
(init-entry-list)
(format t "entry count: ~S~%" (length *entry-list*))

(defvar *menu*)
(setf *menu* (get-menu-by-categories "Network;System"))
(format t "menu: ~S~%" *menu*)
